### ISSUE TITLE
Cached Netowork iMageprovider returns photourl as null, i checked the user model thrice still didn't work

### ISSUE THREAD

**Issue by mohit199thd** [reedbarger/fluttershare#5]
I/om.example.por(16920): Waiting for a blocking GC ProfileSaver
I/om.example.por(16920): WaitForGcToComplete blocked ProfileSaver on ProfileSaver for 44.356ms

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Upload(dirty, dependencies: [_InheritedTheme, MediaQuery, _LocalizationsScope-[GlobalKey#352b9]], state: _UploadState#0932f):
The getter 'photoUrl' was called on null.
Receiver: null
Tried calling: photoUrl

The relevant error-causing widget was: 
  Upload file:///C:/Users/Mohit/port/lib/home.dart:135:11
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _UploadState.uploadForm (package:port/upload.dart:160:84)
#2      _UploadState.build (package:port/upload.dart:170:49)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by gupta-shrinath** [comment]
Can you provide your code?

**Comment by mohit199thd** [comment]
> Can you provide your code?

Thanks for taking a look, its today but I have to start over from the beginning for that
